spring.application.name=evaluationFournisseur
server.port=8009
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=admin
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# infos de chaine de connexion
spring.datasource.url=jdbc:mysql://localhost:3306/SupplierDatabase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
#dialect base de donnees (version)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#logger requettes sql execut?es dans console
spring.jpa.show-sql=true
#desactiver cache ( pour actualiser HTML )
spring.thymeleaf.cache=false
spring.main.allow-circular-references=true
spring.web.resources.add-mappings=true


##

#keycloak.realm=supplier-realm
#keycloak.resource=supplier-client
#keycloak.bearer-only=true
#keycloak.auth-server-url=http://localhost:8080
#keycloak.ssl-required=none


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/supplier-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/supplier-realm/protocol/openid-connect/certs



####


#spring.mail.host=smtp.office365.com
#spring.mail.port=587
#spring.mail.username=acheteur756@gmail.com
#spring.mail.password="zxpu loej hdvx mtuw"
#spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true




#spring.cloud.stream.kafka.binder.configuration.auto.create.topics.enable=true
#spring.cloud.stream.bindings.projectEventConsumer-in-0.destination=R1
spring.cloud.stream.bindings.projectEventConsumer-in-0.destination=R1
spring.cloud.function.definition=projectEventConsumer
#spring.cloud.stream.bindings.projectEventConsumer-in-0.group=project-group
#spring.cloud.stream.kafka.binder.brokers=localhost:9092
#spring.kafka.bootstrap-servers=192.168.0.3:9092
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=producer-1
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*